from enum import Enum


class ErrorCode(str, Enum):
    INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
    INVALID_IMAGE_CONTENT = "INVALID_IMAGE_CONTENT"
    NO_FILE_PROVIDED = "NO_FILE_PROVIDED"
    IMAGE_VALIDATION_ERROR = "IMAGE_VALIDATION_ERROR"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    DUPLICATE_FILE = "DUPLICATE_FILE"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    MODEL_NOT_LOADED = "MODEL_NOT_LOADED"
    PREDICTION_FAILED = "PREDICTION_FAILED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    SECURITY_STATS_RETRIEVAL_ERROR = "SECURITY_STATS_RETRIEVAL_ERROR"
    RATE_LIMIT_NOT_INITIALIZED = "RATE_LIMITER_NOT_INITIALIZED"

    # Authentication
    MISSING_TOKEN = "MISSING_TOKEN"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_AUDIENCE = "INVALID_AUDIENCE"
    TOKEN_VALIDATION_FAILED = "TOKEN_VALIDATION_FAILED"
    AUTH_NOT_CONFIGURED = "AUTH_NOT_CONFIGURED"
    AUTH_DISABLED = "AUTH_DISABLED"
    ADMIN_REQUIRED = "ADMIN_REQUIRED"
    MISSING_CREDENTIALS = "MISSING_CREDENTIALS"
