from enum import Enum

class ErrorCode(str, Enum):
    INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
    INVALID_IMAGE_CONTENT = "INVALID_IMAGE_CONTENT"
    MISSING_FILE = "MISSING_FILE"
    IMAGE_VALIDATION_ERROR = "IMAGE_VALIDATION_ERROR"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    DUPLICATE_FILE = "DUPLICATE_FILE"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    MODEL_NOT_LOADED = "MODEL_NOT_LOADED"
    PREDICTION_FAILED = "PREDICTION_FAILED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"